save:mainSauvegarde.o  Sauvegarde.o 
	gcc mainSauvegarde.o  Sauvegarde.o   -o save -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g
mainSauvegarde.o:mainSauvegarde.c
	gcc -c mainSauvegarde.c  -g
Sauvegarde.o :Sauvegarde.c
	gcc -c Sauvegarde.c  -g
